#!/usr/bin/env bash
# Generate the example fixture file locally. The fixture is NOT committed so that
# platform-side secret scanners (GitHub Push Protection, etc.) don't flag the repo.
#
# Each synthetic value matches one of secret-guard's regexes but is intentionally
# low-entropy / clearly-non-secret. The literal pattern strings only exist once
# this script writes them to disk.
set -euo pipefail

out="${1:-leaked-config.py}"

aws="AKIA$(printf 'A%.0s' {1..16})"
slack="xoxb-0000000000-0000000000-$(printf 'a%.0s' {1..24})"
stripe="sk_live_$(printf 'A%.0s' {1..24})"
gh="ghp_$(printf 'a%.0s' {1..36})"
entropy="MIIEowIBAAKCAQEAm5tHfakeDataNotARealKey1234567890XYZqwerasdfzxcv"

cat > "$out" <<EOF
# DELIBERATELY-FAKE secrets, generated by examples/make-fixture.sh. Do not commit.
AWS_ACCESS_KEY = "$aws"
SLACK_BOT = "$slack"
STRIPE_KEY = "$stripe"
GH_TOKEN = "$gh"
HIGH_ENTROPY = "$entropy"
EOF

echo "wrote $out"
